apiVersion: v1
kind: Service
metadata:
  labels:
    app: sdk-static-test-service
  name: sdk-static-test-service
spec:
  ports:
  - port: 20080
    protocol: TCP
    targetPort: 80
    nodePort: 20080
  selector:
    app: sdk-static-test-service
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sdk-static-test-service-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sdk-static-test-service
    spec:
      nodeName: 172.16.109.119
      containers:
      - name: sdk-static-test-service
        image: hub.sunland2.com:8234/sscp-service/sdk-js-test:<BUILD_TAG>
        ports:
        - containerPort: 80